[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
#  "-Ctarget-feature=+avx2,+sse3,+fma",
  "-Clink-arg=-fuse-ld=lld", # Use LLD Linker
  "-Zshare-generics=y",      # (Nightly) Make the current crate share its generic instantiations

#  Disabled due to: https://github.com/rust-lang/rust/issues/141540
#  "-Zthreads=0",            # (Nightly) Use improved multithreading with the recommended amount of threads.
]

# NOTE: you must install [Mach-O LLD Port](https://lld.llvm.org/MachO/index.html) on mac. you can easily do this by installing llvm which includes lld with the "brew" package manager:
# `brew install llvm`
[target.x86_64-apple-darwin]
rustflags = [
#  "-Ctarget-feature=+avx2,+sse3,+fma",
  "-Clink-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld", # Use LLD Linker
  "-Zshare-generics=y",                                   # (Nightly) Make the current crate share its generic instantiations

#  Disabled due to: https://github.com/rust-lang/rust/issues/141540
#  "-Zthreads=0",            # (Nightly) Use improved multithreading with the recommended amount of threads.
]

[target.aarch64-apple-darwin]
rustflags = [
#  "-Ctarget-feature=+avx2,+sse3,+fma",
  "-Clink-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld", # Use LLD Linker
  "-Zshare-generics=y",                                      # (Nightly) Make the current crate share its generic instantiations

#  Disabled due to: https://github.com/rust-lang/rust/issues/141540
#  "-Zthreads=0",            # (Nightly) Use improved multithreading with the recommended amount of threads.
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe" # Use LLD Linker
rustflags = [
#  "-Ctarget-feature=+avx2,+sse3,+fma",
  "-Zshare-generics=n",

#  Disabled due to: https://github.com/rust-lang/rust/issues/141540
#  "-Zthreads=0",            # (Nightly) Use improved multithreading with the recommended amount of threads.
]

